### ISSUE TITLE
Подробнее

### ISSUE THREAD

**Issue by foshechka** [CheeryLee/VKEncodeMusic#1]
Если можно подробнее. Как запустить? Как работает? Какой функционал?

**Comment by CheeryLee** [comment]
@foshechka , всё очень просто. 
Приложение парсит папку с кэшем ВК (рассматривается только официальная версия, а не всякие модификации), ищет там файлы с расширением ENCODED. 
Сам файл -- закодированная версия обычного МР3. Для кодирования применяется массив-маска на 16 байт. Ее вы можете увидеть в исходнике. Дальше на каждый байт ENCODED накладывается операция "исключающее ИЛИ" с участием байтов из маски. При этом использованный байт в массиве увеличивается на 0х10. И это до тех пор, пока файл не будет до конца перекодирован в изначальный МР3. Готовый файл записывается во внутреннюю память, в папку Music.

Запускать можно на любом устройстве Android с версией системы от 4.4.
