### ISSUE TITLE
Общие вопросы

### ISSUE THREAD

**Issue by IriaSomobu** [CheeryLee/VKEncodeMusic#2]
В принципе, программа работает. НО некоторые вещи мне непонятны:
- [x] Чем обусловлено использование CompatLibraries?
- [x] Зачем использовать ConstraintLayout везде
- [x] Ваша сборка не работает на 4.3 (собранное мной - работает)
- [x] За что принудительная портретная ориентация?
- [x] При повороте экрана сильно тупит (да, знаю что не предназначено)

И еще мелочи.

Вы принимаете PR?

**Comment by CheeryLee** [comment]
@iillyyaa2033 , спасибо за комментарий. Поясню за моменты:
1) я не программирую на Android в принципе, потому некоторые вещи могут быть не оптимизированными. Для меня эта платформа не является основной. Любые полезные правки будут тепло приняты;
2) минимальная версия системы для сборки -- 4.4. Об этом чётко и ясно написано на 4PDA;
3) принудительная, потому что больше всего контента представляется. Не вижу смысла делать ландшафтную;
4) поворот экрана не предусмотрен, отсюда лаги.

Что вы понимаете под PR? Расскажите подробнее, пожалуйста.

**Comment by IriaSomobu** [comment]
PR - Pull Request - грубо говоря, предложение внести коммиты из форка в источник.

Касательно п.2, на OmmiRom (4.4.4) тоже падает.

Возможно, в ближайшее время кину Вам пулл-реквест с правками сверху.

**Comment by CheeryLee** [comment]
Обязательно. Буду рад любым изменениям.
Насчёт OmniROM -- не знаю, нужен лог из logcat. Проверял на своём самсунговском 4.4 -- работало.

**Comment by IriaSomobu** [comment]
Ну, сейчас-то проблема уже решена. Так что в логах если и буду копаться - то разве что под настроение (то бишь не сейчас).

**Comment by IriaSomobu** [comment]
Вот, поправил прогу и создал PR.

Находятся PullRequest'ы в соседней вкладке. Объяснять здесь, как их мержить (merge) не буду - у гитхаба есть хорошая документация. Если возникнут вопросы - пишите мне на почту (указана в профиле) или на 4PDA (но там появляюсь реже).

Удачи!

**Comment by CheeryLee** [comment]
Мержить знаю как, с этим трудностей не возникнет. Большое спасибо за участие в разработке!

**Comment by IriaSomobu** [comment]
Вам спасибо.
