### ISSUE TITLE
Вопрос удаления кэша

### ISSUE THREAD

**Issue by CheeryLee** [CheeryLee/VKEncodeMusic#4]
Программа является перекодировщиком, а значит она должна МЕНЯТЬ форматы файлов. Отсюда подразумевается, что исходного encoded-файла не должно быть после перекодировки.

Жду других мнений.

**Comment by CheeryLee** [comment]
Судя по всему, удаление кэша никому не мешает. Тема закрыта.

**Comment by IriaSomobu** [comment]
Может, в настройки добавить CheckboxPreference 'Удалять кэш после ковертации'?

**Comment by CheeryLee** [comment]
Возможно стоит это рассмотреть.
